# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a5c3b43675964488bc0c42261e989dd8db1462625880de61bc2f1cfab4331127e2240e0c3a2fd352b68073e0764fe95eada4c314bb93dd3cbdfac9a94103291

test:
  secret_key_base: 1d40ac84f5d61afcca882e2e87ec0d3d8bed0136649f43650af2a5d726501bd551bc9873c65ce56ca17cb2afe088a04fe6cdff5189e9000309375b9c9b5c29c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
